//AUTH
export const LOGIN_SUCCESS= "AUTH/LOGIN_SUCCESS"
export const LOGIN_FAIL = "AUTH/LOGIN_FAIL"
export const SIGNUP_SUCCESS = "AUTH/SIGNUP_SUCCESS"
export const SIGNUP_FAIL = "AUTH/SIGNUP_FAIL"
export const LOGOUT = "AUTH/LOGOUT"
export const GET_SESSION_SUCCESS = 'AUTH/GET_SESSION_SUCCESS'
export const GET_SESSION_FAIL = 'AUTH/GET_SESSION_FAIL'
export const GET_AUTH_USER_SUCCESS = 'AUTH/GET_AUTH_USER_SUCCESS'
export const GET_AUTH_USER_FAIL = 'AUTH/GET_AUTH_USER_FAIL'
//APP
export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'
export const SHOW_ALERT = 'APP/SHOW_ALERT'
export const HIDE_ALERT = 'APP/HIDE_ALERT'
